// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-tX7D6B8N9klnabGz2fVZbuExzz2YFc',
    appId: '1:1005390945303:web:0cf5992b0dc434d7ac1052',
    messagingSenderId: '1005390945303',
    projectId: 'tp3-mobile-87e69',
    authDomain: 'tp3-mobile-87e69.firebaseapp.com',
    storageBucket: 'tp3-mobile-87e69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWQTg5jxNZaAohrc8HmiJDfbqdKjrHh0',
    appId: '1:1005390945303:android:e55d9b8ae21acbb6ac1052',
    messagingSenderId: '1005390945303',
    projectId: 'tp3-mobile-87e69',
    storageBucket: 'tp3-mobile-87e69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBe93LpIwVp1-YYX3Y-eBCHJWpau4cr2w',
    appId: '1:1005390945303:ios:4a84874ba106fbd0ac1052',
    messagingSenderId: '1005390945303',
    projectId: 'tp3-mobile-87e69',
    storageBucket: 'tp3-mobile-87e69.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBe93LpIwVp1-YYX3Y-eBCHJWpau4cr2w',
    appId: '1:1005390945303:ios:4a84874ba106fbd0ac1052',
    messagingSenderId: '1005390945303',
    projectId: 'tp3-mobile-87e69',
    storageBucket: 'tp3-mobile-87e69.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM-tX7D6B8N9klnabGz2fVZbuExzz2YFc',
    appId: '1:1005390945303:web:37669fa6fb8e33fdac1052',
    messagingSenderId: '1005390945303',
    projectId: 'tp3-mobile-87e69',
    authDomain: 'tp3-mobile-87e69.firebaseapp.com',
    storageBucket: 'tp3-mobile-87e69.firebasestorage.app',
  );

}